#ifndef EXTERN_INCLUDES_H
#define EXTERN_INCLUDES_H

extern void Delay1Msec12Mhz( uint32_t Delay);
extern void DisplayParameterUpdate(void); 
extern void ProtectionReset(void); 
extern void WriteFlashData(void);
extern void ClearInterruptVariables(void);
extern void UpdateDisplayIndex();
extern void StartCheckCTPolarity(void);
extern  void RefreshLcd(void);
extern void CheckAutoScroll(void);
extern void DisplayDisabled(void);
extern void ReSetDisplayParameter(void);
extern void CalPF(float Error, float * CalGainBufferPointer,float * CalBetaBufferPointer);
extern void EepromWrite(uint16_t DataLocation,uint8_t NoOfBytes,uint8_t DeviceAddress,uint8_t *DataArray );
extern void I2CRead(uint16_t DataLocation,uint8_t NoOfBytes,uint8_t DeviceAddress,uint8_t *DataArray );
extern void CheckEpromFree(uint8_t DeviceAddress);
extern  void DisplayString(uint8_t DV_Row,uint8_t DV_Digit, uint8_t *DV_String,uint8_t LED_Type);
extern  void DisplayCalHighVI(void);
extern  void DisplayCalMidVI(void);
extern  void DisplayCalLowVI(void);
extern  void DisplaySetHighPF(void);
extern  void DisplaySetMidPF(void);
extern  void DisplaySetLowPF(void);
extern  void DisplayCalHighPF(void);
extern  void DisplayCalMidPF(void);
extern  void DisplayCalLowPF(void);
extern void InitUart(uint8_t baud,uint8_t parity1,uint8_t Stopbit1);
extern void ClearCalAccumulatedData(void);
extern void DisplayUpdate(void);
extern void InitializeHardware(void);
extern void DirectCalibration(void);
extern void PowerDownDataSave(void);
extern  void AccumulateDataForCalibration(void);
extern void Metrology(void);
extern void CheckKey(void);
extern void DisplayImproperSettings(void);
extern void UpdateEditSettings(void);
extern void InitWatchDog(void);
extern uint16_t CRCCalculation(uint16_t * str,uint8_t length);
extern  void MeterInit(void);
extern void SetInitialDisplay(void);
extern void SetVersionDisplay(void);
extern void DisplayCheckEnd(void);
extern void CalCtPtRatio(void);
extern void  SaveOldData(void);
extern void SetMeterParameters(void);
extern void FillDefaultValue(void);
extern void InterruptDisplayRefresh(void);
extern void Process1SecInterrupt(void);
extern void ProcessFreqCapture(void);


extern const struct PH_COEFF_STRUCT CalibrationCoeff;
extern struct PH_COEFF_STRUCT CalBuffer;
extern struct INST_PARA InstantPara;
extern struct INT_DATA_SAVE  IntDataSave;
extern struct INT_DATA_SUM   IntDataSum;
extern struct OFFSET         VIOffset;
extern struct FFT_STRUCT     FftSampleData;
extern struct INT_TIMER_COUNT IntTimerCount;
extern struct GAIN_WC WorkingCopyGain;
extern struct STORE TripData;
extern struct Object Timer;
extern const struct Parameter EditParameters[MAX_PARAM_LIMIT];
extern uint16_t CopySetPara[MAX_PARAM_LIMIT+1],MeterPassword;
extern void SaveFlashData(void);
extern void ModBusCommunication(void);
extern volatile uint16_t CounterSendComplete;
extern float CtRatio, PtRatio,CtPtRatio,StartingCurrent;
extern void ProcessMainInterrupt(void);
extern void Metrology(void);
extern uint8_t RecieveArray[MAX_BYTE_TO_RECIEVE],ScrollChangeCounter,DisplayScrollCounter;
extern uint16_t TimerCounter,NoOfBytes;
extern uint8_t ReceiveLength;
extern uint8_t pwrDlyFlag,StartDelayCount,EditPassCount;
extern uint8_t FlagDirectCalibration,CalibrationGapCounter;
extern uint8_t EditParaPassStatus;
extern struct STORE StorageBuffer;
extern  struct STORE OldData;
extern uint8_t PowerFailCounter,EnergyDisplayUnit,PowerUpCounter,ScrollSaveCounter;
extern uint16_t DataSaveCounter;
extern uint32_t CaptureValueSum;
extern uint16_t PreviousCaptureCount,CaptureValueSav,CaptureSumCounter;
extern uint16_t OneSecFlag;
extern struct DIS_SCROLL DisplaySetup ;
extern uint8_t LcdEpromBuffer[128];
extern uint16_t AdcDataInArray[24],SampleCounter;
extern uint32_t InterruptFlag,RYFreqMeasDuration,SaveFreqMeasDuration;
extern uint32_t WattPerPulseTick,IntWattPerPulseTick;
extern uint64_t SumWattPerPulseTick;
extern float IntRPrevSample,IntYPrevSample,IntBPrevSample;
extern uint8_t Tc20ms,OperatingSatatus;
extern uint16_t SwPressed,SwPrev,SwTimer,SwFlag,SwValue,SwTimeOverflow,SwTimeOverflow2,SwTimeOverflow3;
extern int16_t PrevSampleVol,FilOut_1,FilOut_2;
extern uint8_t FreqFlag,CycleCounter,FreqSampleFlag,KWhLedOnCounter;
extern uint32_t Check485DirCount,Check485DirCounter;
extern uint16_t LoadExportOrGenerator;
extern double EnergyOverflowLimit;
extern uint16_t BufferToDisplay[24];
extern uint8_t  KeyPressedCounter,EditIndex,UpdateDisplay;
extern uint8_t ParaBlockIndex,DisplayParameterBuffer[50],dispStartCnt,DisParalast;
extern uint8_t Dec2DCBArray[16];

#endif